export default {
  db: {
    reservedFields: ['DROSSE', 'meta', '$loki'],
  },
  icons: {
    handler: {
      asset: '📁',
      body: '🪝 ',
      service: '🛠️ ',
      static: '📌',
    },
    plugin: {
      proxy: '🔀',
      middleware: '🧩',
      template: '📜',
      throttle: '⏳',
    },
  },
  state: {
    assetsPath: 'assets',
    baseUrl: '',
    basePath: '',
    collectionsPath: 'collections',
    database: 'mocks.json',
    dbAdapter: 'LokiFsAdapter',
    name: 'Drosse mock server',
    port: 8000,
    reservedRoutes: { ui: '/UI', cmd: '/CMD' },
    routesFile: 'routes',
    scrapedPath: 'scraped',
    scraperServicesPath: 'scrapers',
    servicesPath: 'services',
    shallowCollections: [],
    staticPath: 'static',
    uploadPath: 'uploadedFiles',
    uuid: '',
  },
  cli: null,
  commands: {},
  errorHandler: null,
  extendServer: null,
  middlewares: ['morgan'],
  templates: {},
  onHttpUpgrade: null,
}
