export default {
  db: {
    reservedFields: ['DROSSE', 'meta', '$loki'],
  },
  state: {
    assetsPath: 'assets',
    baseUrl: '',
    basePath: '',
    collectionsPath: 'collections',
    database: 'mocks.json',
    dbAdapter: 'LokiFsAdapter',
    name: 'Drosse mock server',
    port: 8000,
    reservedRoutes: { ui: '/UI', cmd: '/CMD' },
    routesFile: 'routes',
    scrapedPath: 'scraped',
    scraperServicesPath: 'scrapers',
    servicesPath: 'services',
    shallowCollections: [],
    staticPath: 'static',
    uuid: '',
  },
  cli: null,
  commands: {},
  errorHandler: null,
  extendServer: null,
  middlewares: [],
  templates: {},
  onHttpUpgrade: null,
}
