name: release artifacts

on: [push]

jobs:
  build_release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: install app dependencies
        run: npm install
      - name: build linux artifact
        if: matrix.platform == 'ubuntu-latest'
        run: make build-linux
      - name: build macos artifact
        if: matrix.platform == 'macos-latest'
        run: make build-macos
      # - name: build windows artifact
      #   if: matrix.platform == 'windows-latest'
      #   run: make build-windows
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            drosse.linux.tar.gz
            drosse.macos.tar.gz